name: Generate Pac-Man Animation

on:
  schedule:
    - cron: "0 */6 * * *"   # update tiap 6 jam
  workflow_dispatch:        # bisa dijalankan manual
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pacman-generator
        run: |
          npm install -g @platane/pacman

      - name: Generate Pac-Man animation
        run: |
          pacman \
            --user-name ${{ github.repository_owner }} \
            --output dist/pacman.svg \
            --color-pacman "#FFD700" \
            --color-dot "#FFFFFF" \
            --color-background "#000000"

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
