name: Generate Snake Animation

on:
  schedule: # auto generate setiap hari
    - cron: "0 0 * * *"
  workflow_dispatch: # bisa dijalankan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: faisnur26
          outputs: dist/snake.svg

      - name: Push Snake Animation to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
